/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.must.istudent.frames;

import com.fasterxml.jackson.databind.JsonNode;
import edu.must.istudent.entity.Student;
import edu.must.istudent.utils.JsonUtil;
import javax.swing.JPanel;

/**
 *
 * @author HiTech
 */
public class StudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentFrame
     */
    Student student = new Student();
    
    public StudentFrame() {
        initComponents();
        this.setVisible(true);
    }
    
    public StudentFrame(Student st) {
        student = st;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        panelLesson = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistSubject = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLesson = new javax.swing.JMenu();
        miLessonList = new javax.swing.JMenuItem();
        miEnroll = new javax.swing.JMenuItem();
        menuSetting = new javax.swing.JMenu();
        miChangePass = new javax.swing.JMenuItem();
        miLanguage = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlistSubject.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlistSubject.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlistSubject);

        javax.swing.GroupLayout panelLessonLayout = new javax.swing.GroupLayout(panelLesson);
        panelLesson.setLayout(panelLessonLayout);
        panelLessonLayout.setHorizontalGroup(
            panelLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLessonLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelLessonLayout.setVerticalGroup(
            panelLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLessonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        layeredPane.setLayer(panelLesson, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
        layeredPane.setLayout(layeredPaneLayout);
        layeredPaneLayout.setHorizontalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addComponent(panelLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layeredPaneLayout.setVerticalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                .addComponent(panelLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuLesson.setText("Lesson");

        miLessonList.setText("Lesson List");
        miLessonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLessonListActionPerformed(evt);
            }
        });
        menuLesson.add(miLessonList);

        miEnroll.setText("Enroll");
        miEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEnrollActionPerformed(evt);
            }
        });
        menuLesson.add(miEnroll);

        jMenuBar1.add(menuLesson);

        menuSetting.setText("Setting");

        miChangePass.setText("Change password");
        menuSetting.add(miChangePass);

        miLanguage.setText("Language");
        miLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLanguageActionPerformed(evt);
            }
        });
        menuSetting.add(miLanguage);

        jMenuBar1.add(menuSetting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLessonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLessonListActionPerformed
        // TODO add your handling code here:
        switchPanels(panelLesson);
        String json = student.getCurrent_studying_subject();
        String result = "";
        JsonNode node = JsonUtil.parse(json);
        node.forEach(x -> System.out.println(x.toString()));
        
        
//        jlistSubject.add(JsonUtil.fromJson(node.get(0), String.class));
        //jlistSubject.setModel(JsonUtil.fromJson(node, String.class));
        
    }//GEN-LAST:event_miLessonListActionPerformed

    private void miLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miLanguageActionPerformed

    private void miEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEnrollActionPerformed
        // TODO add your handling code here:
        //switchPanels(panelEnroll);
    }//GEN-LAST:event_miEnrollActionPerformed

    public void switchPanels(JPanel panel){
        layeredPane.removeAll();
        layeredPane.add(panel);
        layeredPane.repaint();
        layeredPane.revalidate();
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistSubject;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JMenu menuLesson;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JMenuItem miChangePass;
    private javax.swing.JMenuItem miEnroll;
    private javax.swing.JMenuItem miLanguage;
    private javax.swing.JMenuItem miLessonList;
    private javax.swing.JPanel panelLesson;
    // End of variables declaration//GEN-END:variables
}
