/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.must.istudent.frames;

import JsonTest.JsonTest;
import static JsonTest.JsonTest.parse;
import com.fasterxml.jackson.core.JsonProcessingException;
import edu.must.istudent.db.ScoreDB;
import edu.must.istudent.db.TeacherDB;
import edu.must.istudent.entity.Teacher;
import javax.swing.*; 
import java.util.Date;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author HiTech
 */
public class TeacherFrame extends javax.swing.JFrame {

    final static ObjectMapper objectMapper = getDefaultObjectMapper();
    
    private static ObjectMapper getDefaultObjectMapper() {
        ObjectMapper defaultObjectMapper = new ObjectMapper();
        return defaultObjectMapper;
    }
    
    public static JsonNode parse(String src) throws JsonProcessingException {
        return objectMapper.readTree(src);
    }
    
    public static <A> A fromJson(JsonNode node, Class<A> clazz) throws IllegalArgumentException, JsonProcessingException {
        return objectMapper.treeToValue(node, clazz);
    }
    
    ImageIcon img = new ImageIcon("D:\\HICHEEL\\programming\\Data structure and algorithm\\advanced programming\\istudent-main\\istudent-main\\src\\main\\java\\images\\temp.jpg");
    Teacher t = new Teacher();
    public TeacherFrame(String ID) {
        t = TeacherDB.get(ID);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        listTab = new javax.swing.JTabbedPane();
        resume = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        teacherNameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        teacherIDlabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        teacherMobileLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        teacherAgeLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        logOut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        passwordSetting = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        newPasswordLabel = new javax.swing.JLabel();
        newPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newPasswordLabel2 = new javax.swing.JLabel();
        newPassword2 = new javax.swing.JTextField();
        currentPassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        changePassBtn = new javax.swing.JButton();
        resetField = new javax.swing.JButton();
        txtStatus1 = new javax.swing.JLabel();
        addScore = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textLesson = new javax.swing.JTextField();
        textStudentCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDun = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        scoreGPA = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreTable = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        placeOrder = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(241, 244, 248));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        listTab.setBackground(new java.awt.Color(241, 244, 248));
        listTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listTabFocusGained(evt);
            }
        });
        listTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTabMouseClicked(evt);
            }
        });

        resume.setBackground(new java.awt.Color(241, 244, 248));

        jPanel7.setBackground(new java.awt.Color(241, 244, 248));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel.setText("Name :");

        teacherNameLabel.setBackground(new java.awt.Color(241, 244, 248));
        teacherNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherNameLabel.setText(t.getFirst_name() + " " +t.getLast_name());

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idLabel.setText("ID :");

        teacherIDlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherIDlabel.setText(t.getTeacher_id());

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabel.setText("Mobile  :");

        teacherMobileLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherMobileLabel.setText(String.valueOf(t.getMobile()));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("DOB :");

        teacherAgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Date d = t.getDate_of_birth();
        teacherAgeLabel.setText(d.toString());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(idLabel)
                    .addComponent(phoneLabel)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherAgeLabel)
                    .addComponent(teacherMobileLabel)
                    .addComponent(teacherNameLabel)
                    .addComponent(teacherIDlabel))
                .addGap(66, 66, 66))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(teacherNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(teacherIDlabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(teacherAgeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(teacherMobileLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(42, 57, 80));

        jLabel8.setBackground(new java.awt.Color(106, 137, 204));
        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 246, 244));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RESUME");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(163, 163, 163))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        imagePanel.setBackground(new java.awt.Color(241, 244, 248));

        jLabel9.setIcon(img);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(241, 244, 248));
        jPanel8.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        logOut.setBackground(new java.awt.Color(56, 97, 140));
        logOut.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Log out");
        logOut.setFocusPainted(false);
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Teaching subjects :");

        String jsonstr = TeacherDB.getJson();
        String lbl = "";

        try {
            JsonNode json = parse(jsonstr);
            for(int i=0;i<json.size();i++){
                JsonNode node = json.get(i);
                lbl = lbl + node.get("code").asText() + ", ";
            }
        } catch (JsonProcessingException ex) {
            Logger.getLogger(TeacherFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel10.setText(lbl);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout resumeLayout = new javax.swing.GroupLayout(resume);
        resume.setLayout(resumeLayout);
        resumeLayout.setHorizontalGroup(
            resumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resumeLayout.createSequentialGroup()
                .addGroup(resumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, resumeLayout.createSequentialGroup()
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        resumeLayout.setVerticalGroup(
            resumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumeLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        listTab.addTab("Resume", resume);

        jPanel4.setBackground(new java.awt.Color(241, 244, 248));

        newPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPasswordLabel.setText("New Password: ");
        newPasswordLabel.setPreferredSize(new java.awt.Dimension(150, 20));

        newPassword.setBackground(new java.awt.Color(241, 244, 248));
        newPassword.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel6.setText("Change Password :");

        newPasswordLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPasswordLabel2.setText("Re-Enter Password :");
        newPasswordLabel2.setPreferredSize(new java.awt.Dimension(150, 20));

        newPassword2.setBackground(new java.awt.Color(241, 244, 248));
        newPassword2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        newPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassword2ActionPerformed(evt);
            }
        });

        currentPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        currentPassword.setText("Current Password :");
        currentPassword.setPreferredSize(new java.awt.Dimension(150, 20));

        passwordField.setBackground(new java.awt.Color(241, 244, 248));
        passwordField.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        changePassBtn.setBackground(new java.awt.Color(56, 97, 140));
        changePassBtn.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        changePassBtn.setForeground(new java.awt.Color(255, 255, 255));
        changePassBtn.setText("Change");
        changePassBtn.setFocusPainted(false);
        changePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassBtnActionPerformed(evt);
            }
        });

        resetField.setBackground(new java.awt.Color(241, 244, 248));
        resetField.setText("Reset");
        resetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFieldActionPerformed(evt);
            }
        });

        txtStatus1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtStatus1.setForeground(new java.awt.Color(255, 193, 71));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newPasswordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(changePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newPassword)
                            .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newPasswordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout passwordSettingLayout = new javax.swing.GroupLayout(passwordSetting);
        passwordSetting.setLayout(passwordSettingLayout);
        passwordSettingLayout.setHorizontalGroup(
            passwordSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        passwordSettingLayout.setVerticalGroup(
            passwordSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        listTab.addTab("Change Password", passwordSetting);

        addScore.setBackground(new java.awt.Color(241, 244, 248));
        addScore.setPreferredSize(new java.awt.Dimension(557, 360));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Student Code");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lesson Code");

        textLesson.setBackground(new java.awt.Color(241, 244, 248));
        textLesson.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        textLesson.setForeground(new java.awt.Color(56, 97, 140));
        textLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLessonActionPerformed(evt);
            }
        });

        textStudentCode.setBackground(new java.awt.Color(241, 244, 248));
        textStudentCode.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        textStudentCode.setForeground(new java.awt.Color(56, 97, 140));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Score");

        txtDun.setBackground(new java.awt.Color(241, 244, 248));
        txtDun.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtDun.setForeground(new java.awt.Color(56, 97, 140));
        txtDun.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtDunInputMethodTextChanged(evt);
            }
        });
        txtDun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDunKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(56, 97, 140));
        jButton1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(241, 244, 248));
        jButton2.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtStatus.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 193, 71));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel5.setText("Student score :");

        scoreGPA.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        scoreGPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreGPA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        javax.swing.GroupLayout addScoreLayout = new javax.swing.GroupLayout(addScore);
        addScore.setLayout(addScoreLayout);
        addScoreLayout.setHorizontalGroup(
            addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addScoreLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addScoreLayout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addScoreLayout.createSequentialGroup()
                            .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textStudentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addScoreLayout.createSequentialGroup()
                                    .addComponent(txtDun, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(scoreGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel5))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        addScoreLayout.setVerticalGroup(
            addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addScoreLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textStudentCode)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDun, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scoreGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
        );

        listTab.addTab("Add score", addScore);

        tablePanel.setBackground(new java.awt.Color(241, 244, 248));

        jPanel1.setBackground(new java.awt.Color(241, 244, 248));

        try {
            String[] str = new String [] {
                "Student code", "Subject code", "Score"
            };
            String subjectJson = TeacherDB.getJson();
            String subjectList = "";
            JsonNode json = parse(subjectJson);
            for(int i=0;i<json.size();i++){
                JsonNode node = json.get(i);
                subjectList = subjectList + "'" + node.get("code").asText() + "'";
                if(i!=json.size()-1)
                subjectList = subjectList + ",";
            }
            System.out.println(subjectList);
            Object[][] obj = ScoreDB.getScoreList(subjectList,"student_code");
            scoreTable.setBackground(new java.awt.Color(241, 244, 248));
            scoreTable.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                str
            ));
            jScrollPane1.setViewportView(scoreTable);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(TeacherFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        Refresh.setBackground(new java.awt.Color(241, 244, 248));
        Refresh.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.setFocusable(false);
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Order By:");

        placeOrder.setBackground(new java.awt.Color(241, 244, 248));
        placeOrder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "student_code", "subject_code", "score" }));
        placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placeOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        listTab.addTab("Score list", tablePanel);

        jButton3.setText("test");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton3)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButton3)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        listTab.addTab("test", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(listTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listTab, javax.swing.GroupLayout.PREFERRED_SIZE, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTabMouseClicked
 
    }//GEN-LAST:event_listTabMouseClicked

    private void listTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listTabFocusGained
        // TODO add your handling code here:
        String subject_id = t.getTeacher_id();
        Object[][] scorelist = ScoreDB.getScoreList(subject_id,"student_code"); // login hiisen useriing ID-iig techer_id-d hadgalah heregtei bna
        String[] columnNames = {"Student Id","Subject code","Score"};

       
    }//GEN-LAST:event_listTabFocusGained

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void changePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassBtnActionPerformed
        // TODO add your handling code here:
        String str = newPassword.getText();
        String str2 = newPassword2.getText();
        String curr = passwordField.getText();
        
        if(str.equals(str2) && curr.equals(t.getPassword())){
            if(TeacherDB.updatePassword(t.getTeacher_id(), str2)){
                txtStatus1.setText("Password changed!");
            } else{
                txtStatus1.setText("Password not changed!");
            }
        } else if(!str.equals(str2)){
            txtStatus1.setText("Passwords do not match");
        } else txtStatus1.setText("Current password wrong");
    }//GEN-LAST:event_changePassBtnActionPerformed

    private void newPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassword2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String lessonCode = textLesson.getText();
        String studentCode = textStudentCode.getText();
        String dun = txtDun.getText();
        Boolean result = TeacherDB.insertScore(lessonCode, studentCode, Integer.valueOf(dun));

        if(result) {
            txtStatus.setText("successfully added ");
        } else {
            txtStatus.setText("Failed to load score");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void textLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLessonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLessonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        textStudentCode.setText(null);
        textLesson.setText(null);
        txtDun.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDunInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtDunInputMethodTextChanged
        // TODO add your handling code here:       
    }//GEN-LAST:event_txtDunInputMethodTextChanged

    private void txtDunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDunKeyReleased
        // TODO add your handling code here:
        if(txtDun.getText()!=null || txtDun.getText()!=""){
            int score = Integer.parseInt(txtDun.getText());
            if(score>96) scoreGPA.setText("A+");
            else if(score>92) scoreGPA.setText("A");
            else if(score>89) scoreGPA.setText("A-");
            else if(score>86) scoreGPA.setText("B+");
            else if(score>82) scoreGPA.setText("B");
            else if(score>79) scoreGPA.setText("B-");
            else if(score>76) scoreGPA.setText("C+");
            else if(score>72) scoreGPA.setText("C");
            else if(score>69) scoreGPA.setText("C-");
            else if(score>66) scoreGPA.setText("D+");
            else if(score>60) scoreGPA.setText("D");
            else scoreGPA.setText("F");
        }
        else scoreGPA.setText("");
    }//GEN-LAST:event_txtDunKeyReleased

    private void resetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFieldActionPerformed
        // TODO add your handling code here:
        newPassword.setText("");
        newPassword2.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_resetFieldActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        t = new Teacher();
        this.dispose();
        LoginFrame lf = new LoginFrame();
    }//GEN-LAST:event_logOutActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
 
        try {
            String order = (String)placeOrder.getSelectedItem();
            if(order.equals("score")) order = order + " DESC";
            
            String[] str = new String [] {
                "Student code", "Subject code", "Score"
            };
            String subjectJson = TeacherDB.getJson();
            String subjectList = "";
            JsonNode json = parse(subjectJson);
            for(int i=0;i<json.size();i++){
                JsonNode node = json.get(i);
                subjectList = subjectList + "'" + node.get("code").asText() + "'";
                if(i!=json.size()-1)
                    subjectList = subjectList + ",";
            }
            System.out.println(subjectList);
            Object[][] obj = ScoreDB.getScoreList(subjectList,order);
            scoreTable.setBackground(new java.awt.Color(241, 244, 248));

            scoreTable.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                str
            ));

            jScrollPane1.setViewportView(scoreTable);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(TeacherFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_RefreshActionPerformed

    private void placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderActionPerformed
        // TODO add your handling code here:
         try {
            String order = (String)placeOrder.getSelectedItem();
            if(order.equals("score")) order = order + " DESC";
            
            String[] str = new String [] {
                "Student code", "Subject code", "Score"
            };
            String subjectJson = TeacherDB.getJson();
            String subjectList = "";
            JsonNode json = parse(subjectJson);
            for(int i=0;i<json.size();i++){
                JsonNode node = json.get(i);
                subjectList = subjectList + "'" + node.get("code").asText() + "'";
                if(i!=json.size()-1)
                    subjectList = subjectList + ",";
            }
            System.out.println(subjectList);
            Object[][] obj = ScoreDB.getScoreList(subjectList,order);
            scoreTable.setBackground(new java.awt.Color(241, 244, 248));

            scoreTable.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                str
            ));

            jScrollPane1.setViewportView(scoreTable);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(TeacherFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_placeOrderActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
        
        String str = TeacherDB.getJson();
        String lbl = "";
        System.out.println(str);
        
        try {
            JsonNode json = parse(str);
            for(int i=0;i<json.size();i++){
                JsonNode node = json.get(i);
                lbl = lbl + "\n" + node.get("code").asText();
            }
                
        System.out.println(lbl);   
            
        } catch (JsonProcessingException ex) {
            Logger.getLogger(TeacherFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refresh;
    private javax.swing.JPanel addScore;
    private javax.swing.JButton changePassBtn;
    private javax.swing.JLabel currentPassword;
    private javax.swing.JLabel idLabel;
    public javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane listTab;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField newPassword2;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel newPasswordLabel2;
    private javax.swing.JTextField passwordField;
    private javax.swing.JPanel passwordSetting;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JComboBox<String> placeOrder;
    private javax.swing.JButton resetField;
    private javax.swing.JPanel resume;
    private javax.swing.JLabel scoreGPA;
    private javax.swing.JTable scoreTable;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel teacherAgeLabel;
    private javax.swing.JLabel teacherIDlabel;
    private javax.swing.JLabel teacherMobileLabel;
    private javax.swing.JLabel teacherNameLabel;
    private javax.swing.JTextField textLesson;
    private javax.swing.JTextField textStudentCode;
    private javax.swing.JTextField txtDun;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtStatus1;
    // End of variables declaration//GEN-END:variables
}
